name: fit_to_job
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  connectivity_plus: ^2.3.9
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.0.15
  pinput: ^2.2.16
  video_player: ^2.4.7
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  open_file: ^2.1.1
  http: ^0.13.5
  path_provider: ^2.0.11
  lottie: ^1.4.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

 
