import 'package:fit_to_job/LocalStorage/SaveCredential.dart';

import '../../Screens/Authentication/login_screen.dart';
import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import '../../Screens/Constant/apiPath.dart';
import '../../Screens/Widgets/hepler.dart';

Future registerAPI(
    {String aadharCardNo,
    String firstName,
    String middleName,
    String lastName,
    String mobileNo,
    String city,
    String taluka,
    String district,
    String state,
    String address,
    BuildContext context}) async {
  final response = await http.post(Uri.parse(registerAPIURL), body: {
    "aadharCardNo": aadharCardNo,
    "firstName": firstName,
    "middleName": middleName,
    "lastName": lastName,
    "mobileNo": mobileNo,
    "city": city,
    "taluka": taluka,
    "district": district,
    "state": state,
    "address": address,
  });
  var data = json.decode(response.body);
  if (data['status'] == "200") {
    ScaffoldMessenger.of(context).showSnackBar(customSnackbar(
        label: "Login Now",
        lColor: Colors.white,
        time: const Duration(seconds: 8),
        press: () => Navigator.push(context,
            MaterialPageRoute(builder: (context) => const LoginScreen())),
        msg: "User Registered Successfully",
        chooseColor: Colors.green));
    Navigator.push(
        context, MaterialPageRoute(builder: (context) => const LoginScreen()));

    debugPrint("Register Succesfully");
    debugPrint(data['result']);
  } else {
    ScaffoldMessenger.of(context).showSnackBar(customSnackbar(
        label: "Login Now",
        lColor: Colors.white,
        time: const Duration(seconds: 8),
        press: () => Navigator.push(context,
            MaterialPageRoute(builder: (context) => const LoginScreen())),
        msg: "User Already Exist",
        chooseColor: Colors.red));
    debugPrint("Not register");
  }
}

// OTP Verification
//111111111111
//6355260464

// Future InterviewAPI(
//     {
//       String YourPhoto,
//     String FullName,
//     String PresentAddress,
//     String PresentPost,
//     String PresentVillage,
//     String PresentDistrict,
//     String PresentPinCode,
//     String PresentMobileNo,
//     String PermanentAddress,
//     String PermanentPost,
//     String PermanentVillage,
//     String PermanentDistrict,
//     String PermanentPinCode,
//     String PermanentMobileNo,
//     String YourDOB,
//     String YourBloodGroup,
//     String YourAadharCardNo,
//     String YourPanCardNo,
//     String YourElectionCardNo,
//     String YourCategory,
//     String YourEmail,
//     String FatherName,
//     String FatherOccupation,
//     String FatherEducation,
//     String FatherMobileNo,
//     String MotherName,
//     String MotherOccupation,
//     String MotherEducation,
//     String MotherMobileNo,
//     String WifeName,
//     String WifeOccupation,
//     String WifeEducation,
//     String WifeMobileNo,
//     String BrotherName,
//     String BrotherOccupation,
//     String BrotherEducation,
//     String BrotherMobileNo,
//     String NomineeName,
//     String NomineeDOB,
//     String NomineeRelation,
//     String NomineeAge,
//     String Standanrd10Subject,
//     String Standanrd10PassingYear,
//     String Standanrd10Percentage,
//     String Standanrd12Subject,
//     String Standanrd12PassingYear,
//     String Standanrd12Percentage,
//     String GraduateSubject,
//     String GraduatePassingYear,
//     String GraduatePercentage,
//     String PostGraduateSubject,
//     String PostGraduatePassingYear,
//     String PostGraduatePercentage,
//     String OtherSubject,
//     String OtherPassingYear,
//     String OtherPercentage,
//     String CertificateCourseName,
//     String CertificateCourseYear,
//     String TrainingName,
//     String TrainingYear,
//     String MedalName,
//     String MedalYear,
//     String FirstCompanyName,
//     String FirstCompanyDesignation,
//     String FirstCompanyExp,
//     String FirstCompanySalary,
//     String SecondCompanyName,
//     String SecondCompanyDesignation,
//     String SecondCompanyExp,
//     String SecondCompanySalary,
//     String ThirdCompanyName,
//     String ThirdCompanyDesignation,
//     String ThirdCompanyExp,
//     String ThirdCompanySalary,
//     String OtherExpNoExpDetails,
//     String Document1,
//     String Document2,
//     String Document3,
//     String Document4,
//     String Document5,
//     String Document6,
//     String Document1PathOne,
//     String Document1PathTwo,
//     String Document2PathOne,
//     String Document2PathTwo,
//     String Document3PathOne,
//     String Document3PathTwo,
//     String Document4PathOne,
//     String Document4PathTwo,
//     String Document5PathOne,
//     String Document5PathTwo,
//     String Document6PathOne,
//     String Document6PathTwo,
//     String DukeReferenceName,
//     String DukeReferenceSign,
//     String OtherReferenceName,
//     String OtherReferenceSign,



//     // change krni hogi 
   
//     BuildContext context}) async {
//   final response = await http.post(Uri.parse(interviewformAPIURL), body: {
//     "YourPhoto": YourPhoto,
//     "FullName": FullName,
//     "PresentAddress": PresentAddress,
//     "PresentPost": PresentPost,
//     "PresentVillage": PresentVillage,
//     "PresentDistrict": PresentDistrict,
//     "PresentPinCode": PresentPinCode,
//     "PresentMobileNo": PresentMobileNo,
//     "PermanentAddress": PermanentAddress,
//     "PermanentPost": PermanentPost,
//     "PermanentVillage": PermanentVillage,
//     "PermanentDistrict": PermanentDistrict,
//     "PermanentPinCode": PermanentPinCode,
//     "PermanentMobileNo": PermanentMobileNo,
//     "YourDOB": YourDOB,
//     "YourBloodGroup": YourBloodGroup,
//     "YourAadharCardNo": YourAadharCardNo,
//     "YourPanCardNo": YourPanCardNo,
//     "YourElectionCardNo": YourElectionCardNo,
//     "YourCategory": YourCategory,
//     "YourEmail": YourEmail,
//     "FatherName": FatherName,
//     "FatherOccupation": FatherOccupation,
//     "FatherEducation": FatherEducation,
//     "FatherMobileNo": FatherMobileNo,
//     "MotherName": MotherName,
//     "MotherOccupation": MotherOccupation,
//     "MotherEducation": MotherEducation,
//     "MotherMobileNo": MotherMobileNo,
//     "WifeName": WifeName,
//     "WifeOccupation": WifeOccupation,
//     "WifeEducation": WifeEducation,
//     "WifeMobileNo": WifeMobileNo,
//     "BrotherName": BrotherName,
//     "BrotherOccupation": BrotherOccupation,
//     "BrotherEducation": BrotherEducation,
//     "BrotherMobileNo": BrotherMobileNo,
//     "NomineeName": NomineeName,
//     "NomineeDOB": NomineeDOB,
//     "NomineeRelation": NomineeRelation,
//     "NomineeAge": NomineeAge,
//     "Standanrd10Subject": Standanrd10Subject,
//     "Standanrd10PassingYear": Standanrd10PassingYear,
//     "Standanrd10Percentage": Standanrd10Percentage,
//     "Standanrd12Subject": Standanrd12Subject,
//     "Standanrd12PassingYear": Standanrd12PassingYear,
//     "Standanrd12Percentage": Standanrd12Percentage,
//     "GraduateSubject": GraduateSubject,
//     "GraduatePassingYear": GraduatePassingYear,
//     "GraduatePercentage": GraduatePercentage,
//     "PostGraduateSubject": PostGraduateSubject,
//     "PostGraduatePassingYear": PostGraduatePassingYear,
//     "PostGraduatePercentage": PostGraduatePercentage,
//     "OtherSubject": OtherSubject,
//     "OtherPassingYear": OtherPassingYear,
//     "OtherPercentage": OtherPercentage,
//     "CertificateCourseName": CertificateCourseName,
//     "CertificateCourseYear": CertificateCourseYear,
//     "TrainingName": TrainingName,
//     "TrainingYear": TrainingYear,
//     "MedalName": MedalName,
//     "MedalYear": MedalYear,
//     "FirstCompanyName": FirstCompanyName,
//     "FirstCompanyDesignation": FirstCompanyDesignation,
//     "FirstCompanyExp": FirstCompanyExp,
//     "FirstCompanySalary": FirstCompanySalary,
//     "SecondCompanyName": SecondCompanyName,
//     "SecondCompanyDesignation": SecondCompanyDesignation,
//     "SecondCompanyExp": SecondCompanyExp,
//     "SecondCompanySalary": SecondCompanySalary,
//     "ThirdCompanyName": ThirdCompanyName,
//     "ThirdCompanyDesignation": ThirdCompanyDesignation,
//     "ThirdCompanyExp": ThirdCompanyExp,
//     "ThirdCompanySalary": ThirdCompanySalary,
//     "OtherExpNoExpDetails": OtherExpNoExpDetails,
//     "Document1 ": Document1,
//     "Document2 ": Document2,
//     "Document3 ": Document3,
//     "Document4 ": Document4,
//     "Document5": Document5,
//     "Document6 ": Document6,
//     "Document1PathOne ": Document1PathOne,
//     "Document1PathTwo": Document1PathTwo,
//     "Document2PathOne ": Document2PathOne,
//     "Document2PathTwo": Document2PathTwo,
//     "Document3PathOne": Document3PathOne,
//     "Document3PathTwo": Document3PathTwo,
//     "Document4PathOne": Document4PathOne,
//     "Document4PathTwo": Document4PathTwo,
//     "Document5PathOne": Document5PathOne,
//     "Document5PathTwo": Document5PathTwo,
//     "Document6PathOne": Document6PathOne,
//     "Document6PathTwo": Document6PathTwo,
//     "DukeReferenceName": DukeReferenceName,
//     "DukeReferenceSign": DukeReferenceSign,
//     "OtherReferenceName": OtherReferenceName,
//     "OtherReferenceSign": OtherReferenceSign,
//   });
//   var data = json.decode(response.body);
//   if (data['status'] == "200") {
  
//     debugPrint("Data saved Succesfully");
//     debugPrint(data['result']);
//   } else {
//     debugPrint("Not register");
//   }
// }


  